test_that("use", {
  expect_equal(window_kb_to_n_associations("IL-17RA", 1), 2)
  expect_equal(window_kb_to_n_associations("IL-17RA", 10), 4)
  expect_equal(window_kb_to_n_associations("IL-17RA", 100), 5)
  expect_equal(window_kb_to_n_associations("IL-17RA", 1000), 6)
  expect_equal(window_kb_to_n_associations("IL-6RA", 1), 1)
  expect_equal(window_kb_to_n_associations("IL-6RA", 10), 1)
  expect_equal(window_kb_to_n_associations("IL-6RA", 100), 3)
  expect_equal(window_kb_to_n_associations("IL-6RA", 1000), 3)
  expect_error(window_kb_to_n_associations("Nonsense", 1))
  expect_error(window_kb_to_n_associations("IL-6RA", -123))
})
