test_that("use", {
  expect_equal(window_kb_to_n_associations("IL-17RA", 1), 2)
  expect_equal(window_kb_to_n_associations("IL-17RA", 10), 5)
  expect_equal(window_kb_to_n_associations("IL-17RA", 100), 5)
  expect_equal(window_kb_to_n_associations("IL-17RA", 1000), 6)
  expect_error(window_kb_to_n_associations("IL-17RA", 0))
  expect_error(window_kb_to_n_associations("IL-17RA", 10000))
  expect_equal(window_kb_to_n_associations("IL-6RA", 1), 1)
  expect_equal(window_kb_to_n_associations("IL-6RA", 10), 1)
  expect_equal(window_kb_to_n_associations("IL-6RA", 100), 1)
  expect_equal(window_kb_to_n_associations("IL-6RA", 1000), 1)
  expect_error(window_kb_to_n_associations("IL-6RA", 0))
  expect_error(window_kb_to_n_associations("IL-6RA", 10000))
  expect_error(window_kb_to_n_associations("Nonsense", 1))
})
