Bootstrap: library
From: anna872/default/python38:latest

%post
    python3 -m pip install -r ../GenoCAE/requirements.txt    

%runscript
exec R --vanilla --silent --no-echo "$@"

%test
    python3 ../GenoCAE/run_gcae.py --help

%help

This container installs the Python packages needed by GCAE installed.

To make the container run a script called, e.g. `run_gcae.py`, do:

```
cat run_gcae.py | ./nsphs_ml_qt.sif
```

%labels

    AUTHOR Richel J.C. Bilderbeek

    NAME nsphs_ml_qt

    DESCRIPTION The nsphs_ml_qt project

    USAGE send a Python script to the container, e.g. `cat run_gcae.py | ./nsphs_ml_qt.sif`

    URL https://github.com/richelbilderbeek/nsphs_ml_qt

    VERSION 0.1
